name: Weekly Update

permissions:
  contents: write

on:
  schedule:
    - cron: '0 21 * * 0'  # 毎週月曜6:00 JST（UTC基準）
  workflow_dispatch:      # 手動実行も可能

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリを取得
        uses: actions/checkout@v3

      - name: Pythonセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: ライブラリインストール
        run: |
          pip install -r requirements.txt

      - name: スクリプト実行
        run: |
          python generate.py

      - name: 自動コミット
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "自動更新"
          git push

